update first yaml file 3nd

diff --git a/.github/workflows/01-building-blocks.yaml b/.github/workflows/01-building-blocks.yaml
--- a/.github/workflows/01-building-blocks.yaml
+++ b/.github/workflows/01-building-blocks.yaml
@@ -1,7 +1,6 @@
 name: 01-building-blocks
 
-on:
-  push
+on: push
 jobs:
   echo-hello:
     runs-on: ubuntu-latest
@@ -12,7 +11,8 @@ jobs:
     runs-on: ubuntu-latest
     steps:
       - name: Failed step
-        run: echo "I will fail"
-          exit 1
+        run: |
+            echo "I will fail"
+            exit 1
       - name: Say Goodbye
         run: echo "Goodbye!"
